services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: teste123
      MYSQL_DATABASE: cashflow
      MYSQL_USER: kayo
      MYSQL_PASWORD: teste123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
        
volumes:
  mysql-data: